"""Turn results/*.csv into RESULTS.md and two charts in plots/.

Run after bench_gemm, bench_attention and bench_sdpa.py have written their CSV
files (run_all.sh does all of this). Needs matplotlib.
"""

import csv
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import FixedLocator, FuncFormatter, LogLocator, NullLocator

HERE = Path(__file__).resolve().parent
RESULTS, PLOTS = HERE / "results", HERE / "plots"
TOL = 1e-3  # max abs / rel error that still counts as correct

# Chart colours: categorical slots 1-4 of a colour-blind-checked palette, fixed order.
SLOTS = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100"]
MARKERS = ["o", "s", "^", "D"]
INK, INK_2, GRID, SURFACE = "#0b0b0b", "#52514e", "#e4e3de", "#fcfcfb"


def read_csv(name):
    path = RESULTS / name
    if not path.exists():
        return []
    with open(path) as f:
        return [r for r in csv.DictReader(line for line in f if not line.startswith("["))]


def num(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def fmt(x, digits=1):
    return "–" if x is None else f"{x:,.{digits}f}"


def fmt_ms(x):
    """Milliseconds with 3 significant digits below 1 ms."""
    if x is None:
        return "–"
    return f"{x:,.2f}" if x >= 1 else f"{x:.3g}"


def pick(rows, **match):
    return {int(r["N"] if "N" in r else r["m"]): r for r in rows
            if all(r.get(k) == v for k, v in match.items())}


def line_chart(path, title, xlabel, ylabel, series, xs):
    """series: list of (label, {x: y}). Log-log line chart with direct end labels."""
    fig, ax = plt.subplots(figsize=(8, 4.5), dpi=200)
    fig.patch.set_facecolor(SURFACE)
    ax.set_facecolor(SURFACE)
    for i, (label, points) in enumerate(series):
        px = [x for x in xs if points.get(x) is not None]
        py = [points[x] for x in px]
        if not px:
            continue
        ax.plot(px, py, color=SLOTS[i], lw=1.5, marker=MARKERS[i], ms=6,
                markeredgecolor=SURFACE, markeredgewidth=1, label=label, zorder=3)
        ax.annotate(label, (px[-1], py[-1]), xytext=(8, 0), textcoords="offset points",
                    va="center", fontsize=8, color=INK_2)
    ax.set_xscale("log", base=2)
    ax.set_yscale("log")
    ax.xaxis.set_major_locator(FixedLocator(xs))
    ax.xaxis.set_minor_locator(NullLocator())
    ax.xaxis.set_major_formatter(FuncFormatter(lambda v, _: f"{int(v):,}"))
    ax.yaxis.set_major_locator(LogLocator(base=10, subs=(1.0, 2.0, 5.0)))
    ax.yaxis.set_minor_locator(NullLocator())
    ax.yaxis.set_major_formatter(FuncFormatter(lambda v, _: f"{v:,.0f}" if v >= 1 else f"{v:g}"))
    ax.set_xlim(xs[0] / 1.3, xs[-1] * 2.6)  # room for end labels
    ax.set_title(title, loc="left", fontsize=11, color=INK)
    ax.set_xlabel(xlabel, fontsize=9, color=INK_2)
    ax.set_ylabel(ylabel, fontsize=9, color=INK_2)
    ax.grid(True, which="major", color=GRID, lw=0.6)
    ax.tick_params(colors=INK_2, labelsize=8)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(GRID)
    ax.legend(frameon=False, fontsize=8, labelcolor=INK_2, loc="upper center",
              bbox_to_anchor=(0.5, -0.16), ncol=len(series))
    fig.tight_layout()
    fig.savefig(path, facecolor=SURFACE)
    plt.close(fig)


def main():
    PLOTS.mkdir(exist_ok=True)
    env = (RESULTS / "env.txt").read_text().strip() if (RESULTS / "env.txt").exists() else "unknown"
    gemm = read_csv("gemm.csv")
    attn = read_csv("attention.csv") + read_csv("sdpa.csv")
    out = ["# Benchmark results", "",
           "Generated by `bench/run_all.sh`. All course kernels are FP32. Times are the median of repeated runs "
           "measured with CUDA events.", "", "```", env, "```", ""]

    # ---------- GEMM ----------
    if gemm:
        w2, w3, cb = pick(gemm, kernel="week2_tiled"), pick(gemm, kernel="week3_regblock"), pick(gemm, kernel="cublas")
        sizes = sorted(cb)
        out += ["## GEMM (square, FP32)", "", "![GEMM throughput](plots/gemm.png)", "",
                "| Size | Week 2 tiled (GFLOPS) | Week 3 register-blocked (GFLOPS) | cuBLAS (GFLOPS) "
                "| Week 3 as % of cuBLAS | Max rel. error vs cuBLAS (wk2 / wk3) |",
                "|---:|---:|---:|---:|---:|---|"]
        for s in sizes:
            g2, g3, gc = (num(d.get(s, {}).get("gflops")) for d in (w2, w3, cb))
            pct = f"{100 * g3 / gc:.0f}%" if g3 and gc else "–"
            errs = " / ".join(w.get(s, {}).get("max_rel_err_vs_cublas", "–") for w in (w2, w3))
            out.append(f"| {s:,} | {fmt(g2, 0)} | {fmt(g3, 0)} | {fmt(gc, 0)} | {pct} | {errs} |")
        out.append("")
        line_chart(PLOTS / "gemm.png", "GEMM throughput, FP32 (higher is better)", "Matrix size (M = N = K)",
                   "GFLOPS (log scale)",
                   [(name, {s: num(d[s]["gflops"]) for s in d}) for name, d in
                    [("Week 2 tiled", w2), ("Week 3 register-blocked", w3), ("cuBLAS", cb)]], sizes)

    # ---------- Attention ----------
    if attn:
        series = [("week4_flash", "Week 4 FlashAttention"), ("week5_fa2", "Week 5 FlashAttention-2"),
                  ("sdpa_fp32", "PyTorch SDPA FP32"), ("sdpa_fp16", "PyTorch SDPA FP16 (flash)")]
        fwd = {k: pick(attn, kernel=k, **{"pass": "fwd"}) for k, _ in series}
        bwd = {k: pick(attn, kernel=k, **{"pass": "bwd"}) for k, _ in series}
        lens = sorted({n for d in fwd.values() for n in d})

        def ms(table, k, n):
            return num(table[k].get(n, {}).get("ms"))

        out += ["## Attention forward (one head, d = 64, no mask)", "",
                "![Attention forward throughput](plots/attention_fwd.png)", "",
                "| N | Week 4 (ms) | Week 5 FA2 (ms) | SDPA FP32 (ms) | SDPA FP16 (ms) | FA2 vs SDPA FP32 |",
                "|---:|---:|---:|---:|---:|---:|"]
        for n in lens:
            f2, s32 = ms(fwd, "week5_fa2", n), ms(fwd, "sdpa_fp32", n)
            ratio = f"{f2 / s32:.1f}× slower" if f2 and s32 else "–"
            w4 = fwd["week4_flash"].get(n, {})
            w4_cell = "skipped" if "skipped" in w4.get("err_detail", "") else fmt_ms(ms(fwd, "week4_flash", n))
            out.append(f"| {n:,} | {w4_cell} | {fmt_ms(f2)} | {fmt_ms(s32)} | {fmt_ms(ms(fwd, 'sdpa_fp16', n))} | {ratio} |")
        out += ["", "## Attention backward", "",
                "| N | Week 5 FA2 (ms) | SDPA FP32 (ms) | SDPA FP16 (ms) | FA2 vs SDPA FP32 |",
                "|---:|---:|---:|---:|---:|"]
        for n in lens:
            b2, b32 = ms(bwd, "week5_fa2", n), ms(bwd, "sdpa_fp32", n)
            ratio = f"{b2 / b32:.1f}× slower" if b2 and b32 else "–"
            out.append(f"| {n:,} | {fmt_ms(b2)} | {fmt_ms(b32)} | {fmt_ms(ms(bwd, 'sdpa_fp16', n))} | {ratio} |")
        out.append("")
        line_chart(PLOTS / "attention_fwd.png", "Attention forward throughput (higher is better)",
                   "Sequence length N", "TFLOPS (log scale)",
                   [(label, {n: num(r.get("tflops")) for n, r in fwd[k].items()}) for k, label in series], lens)

        # ---------- Correctness ----------
        checked = [r for r in read_csv("attention.csv") if r.get("max_abs_err")]
        if checked:
            out += ["## Correctness (vs the CPU references in each week's file)", "",
                    f"Checked for N ≤ 1,024. An error above {TOL:g} is marked **FAIL**.", "",
                    "| Kernel | Pass | N | Max abs. error | Detail | Result |", "|---|---|---:|---:|---|---|"]
            for r in checked:
                e = num(r["max_abs_err"])
                verdict = "ok" if e is not None and e <= TOL else "**FAIL**"
                out.append(f"| {r['kernel']} | {r['pass']} | {int(r['N']):,} | {r['max_abs_err']} "
                           f"| {r['err_detail'].replace(';', ', ')} | {verdict} |")
            out.append("")

    (HERE / "RESULTS.md").write_text("\n".join(out))
    print(f"Wrote {HERE / 'RESULTS.md'} and charts in {PLOTS}")


if __name__ == "__main__":
    main()
